import sys
from pathlib import Path

FORMAT_CONFIG_PATH = str(Path(sys.argv[1]).resolve())

PATH = str(Path(sys.argv[2]).resolve())

with open(FORMAT_CONFIG_PATH, "r") as f:
    config = f.read()
    CONFIG = f"""
## This file was generated by makeFluidSynthConfig.py

{config}

## End of generated file""".format(PATH=PATH)

with open(FORMAT_CONFIG_PATH + ".generated", "w") as f:
    f.write(CONFIG)
